# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/karim/Bureau/Bowling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/karim/Bureau/Bowling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karim/Bureau/Bowling/CMakeFiles /home/karim/Bureau/Bowling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karim/Bureau/Bowling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bowling

# Build rule for target.
bowling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bowling
.PHONY : bowling

# fast build rule for target.
bowling/fast:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/build
.PHONY : bowling/fast

#=============================================================================
# Target rules for targets named bowling_test

# Build rule for target.
bowling_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bowling_test
.PHONY : bowling_test

# fast build rule for target.
bowling_test/fast:
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/build
.PHONY : bowling_test/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f include/googletest/CMakeFiles/gtest.dir/build.make include/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f include/googletest/CMakeFiles/gtest_main.dir/build.make include/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/bowling.o: src/bowling.cpp.o

.PHONY : src/bowling.o

# target to build an object file
src/bowling.cpp.o:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/src/bowling.cpp.o
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/src/bowling.cpp.o
.PHONY : src/bowling.cpp.o

src/bowling.i: src/bowling.cpp.i

.PHONY : src/bowling.i

# target to preprocess a source file
src/bowling.cpp.i:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/src/bowling.cpp.i
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/src/bowling.cpp.i
.PHONY : src/bowling.cpp.i

src/bowling.s: src/bowling.cpp.s

.PHONY : src/bowling.s

# target to generate assembly for a file
src/bowling.cpp.s:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/src/bowling.cpp.s
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/src/bowling.cpp.s
.PHONY : src/bowling.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bowling.dir/build.make CMakeFiles/bowling.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/bowling_test.o: test/bowling_test.cpp.o

.PHONY : test/bowling_test.o

# target to build an object file
test/bowling_test.cpp.o:
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/test/bowling_test.cpp.o
.PHONY : test/bowling_test.cpp.o

test/bowling_test.i: test/bowling_test.cpp.i

.PHONY : test/bowling_test.i

# target to preprocess a source file
test/bowling_test.cpp.i:
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/test/bowling_test.cpp.i
.PHONY : test/bowling_test.cpp.i

test/bowling_test.s: test/bowling_test.cpp.s

.PHONY : test/bowling_test.s

# target to generate assembly for a file
test/bowling_test.cpp.s:
	$(MAKE) -f CMakeFiles/bowling_test.dir/build.make CMakeFiles/bowling_test.dir/test/bowling_test.cpp.s
.PHONY : test/bowling_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bowling"
	@echo "... bowling_test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/bowling.o"
	@echo "... src/bowling.i"
	@echo "... src/bowling.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/bowling_test.o"
	@echo "... test/bowling_test.i"
	@echo "... test/bowling_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

